micronaut:
  application:
    name: todoApp
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/todo_db?currentSchema=todo-app-schema
    driverClassName: org.postgresql.Driver
    username: rneri
    password: postgres
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
